### PR TITLE
Logalleon patch 1

### PR DESCRIPTION
**Pull request by logalleon**
@rpersche @smallela1

### CODE REVIEW

**Comment by rpersche** [comment]
What is with the other two files loaded from cloudfare?

**Comment by rpersche** [comment]
@smallela1  can you find the includes and fix them too?




<title>Login - CAS &#8211; Central Authentication Service</title>
  | <meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/><link type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/><link rel="stylesheet" href="/cas/css/cas.css"/><link rel="icon" href="/cas/favicon.ico" type="image/x-icon"/><script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.3.0/zxcvbn.js"></script>
  | <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

**Comment by rpersche** [comment]
@smallela1 
 <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

**Comment by smallela1** [comment]
@rpersche @logalleon  I have committed the changes. Can you please pull and test it locally. If all good, please merge.

**Comment by rpersche** [comment]
@logalleon @smallela1  I feel there are too many changes but I don't have time to review. Please be careful.

**Pull request merged**
